/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteRouteImport } from './routes/setup/route'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as CheckoutRouteRouteImport } from './routes/checkout/route'
import { Route as CartRouteRouteImport } from './routes/cart/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as PaymentOrderNumberRouteImport } from './routes/payment/$orderNumber'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AdminProductsRouteRouteImport } from './routes/admin/products/route'
import { Route as AdminOrdersRouteRouteImport } from './routes/admin/orders/route'
import { Route as AdminMediaRouteRouteImport } from './routes/admin/media/route'
import { Route as AdminInventoryRouteRouteImport } from './routes/admin/inventory/route'
import { Route as AdminEmailsRouteRouteImport } from './routes/admin/emails/route'
import { Route as AdminCouponsRouteRouteImport } from './routes/admin/coupons/route'
import { Route as AdminContentRouteRouteImport } from './routes/admin/content/route'
import { Route as AdminCategoriesRouteRouteImport } from './routes/admin/categories/route'
import { Route as AdminActivityRouteRouteImport } from './routes/admin/activity/route'
import { Route as AccountOrdersRouteRouteImport } from './routes/account/orders/route'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'
import { Route as AccountOrdersOrderNumberRouteImport } from './routes/account/orders/$orderNumber'

const SetupRouteRoute = SetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRouteRoute = CartRouteRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const PaymentOrderNumberRoute = PaymentOrderNumberRouteImport.update({
  id: '/payment/$orderNumber',
  path: '/payment/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRouteRoute = AdminProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRouteRoute = AdminOrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRouteRoute = AdminMediaRouteRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRouteRoute = AdminInventoryRouteRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailsRouteRoute = AdminEmailsRouteRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCouponsRouteRoute = AdminCouponsRouteRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRouteRoute = AdminContentRouteRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRouteRoute = AdminCategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivityRouteRoute = AdminActivityRouteRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountOrdersRouteRoute = AccountOrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRouteRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountOrdersRouteRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRouteRoute,
} as any)
const AccountOrdersOrderNumberRoute =
  AccountOrdersOrderNumberRouteImport.update({
    id: '/$orderNumber',
    path: '/$orderNumber',
    getParentRoute: () => AccountOrdersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/cart': typeof CartRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/login': typeof LoginRouteRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/register': typeof RegisterRouteRoute
  '/setup': typeof SetupRouteRoute
  '/account/orders': typeof AccountOrdersRouteRouteWithChildren
  '/admin/activity': typeof AdminActivityRouteRoute
  '/admin/categories': typeof AdminCategoriesRouteRoute
  '/admin/content': typeof AdminContentRouteRoute
  '/admin/coupons': typeof AdminCouponsRouteRoute
  '/admin/emails': typeof AdminEmailsRouteRoute
  '/admin/inventory': typeof AdminInventoryRouteRoute
  '/admin/media': typeof AdminMediaRouteRoute
  '/admin/orders': typeof AdminOrdersRouteRouteWithChildren
  '/admin/products': typeof AdminProductsRouteRoute
  '/admin/settings': typeof AdminSettingsRouteRoute
  '/api/health': typeof ApiHealthRoute
  '/payment/$orderNumber': typeof PaymentOrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/login': typeof LoginRouteRoute
  '/register': typeof RegisterRouteRoute
  '/setup': typeof SetupRouteRoute
  '/admin/activity': typeof AdminActivityRouteRoute
  '/admin/categories': typeof AdminCategoriesRouteRoute
  '/admin/content': typeof AdminContentRouteRoute
  '/admin/coupons': typeof AdminCouponsRouteRoute
  '/admin/emails': typeof AdminEmailsRouteRoute
  '/admin/inventory': typeof AdminInventoryRouteRoute
  '/admin/media': typeof AdminMediaRouteRoute
  '/admin/products': typeof AdminProductsRouteRoute
  '/admin/settings': typeof AdminSettingsRouteRoute
  '/api/health': typeof ApiHealthRoute
  '/payment/$orderNumber': typeof PaymentOrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/cart': typeof CartRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/login': typeof LoginRouteRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/register': typeof RegisterRouteRoute
  '/setup': typeof SetupRouteRoute
  '/account/orders': typeof AccountOrdersRouteRouteWithChildren
  '/admin/activity': typeof AdminActivityRouteRoute
  '/admin/categories': typeof AdminCategoriesRouteRoute
  '/admin/content': typeof AdminContentRouteRoute
  '/admin/coupons': typeof AdminCouponsRouteRoute
  '/admin/emails': typeof AdminEmailsRouteRoute
  '/admin/inventory': typeof AdminInventoryRouteRoute
  '/admin/media': typeof AdminMediaRouteRoute
  '/admin/orders': typeof AdminOrdersRouteRouteWithChildren
  '/admin/products': typeof AdminProductsRouteRoute
  '/admin/settings': typeof AdminSettingsRouteRoute
  '/api/health': typeof ApiHealthRoute
  '/payment/$orderNumber': typeof PaymentOrderNumberRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/products'
    | '/register'
    | '/setup'
    | '/account/orders'
    | '/admin/activity'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/emails'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/api/health'
    | '/payment/$orderNumber'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/products/'
    | '/account/orders/$orderNumber'
    | '/admin/orders/$id'
    | '/account/orders/'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/register'
    | '/setup'
    | '/admin/activity'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/emails'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/products'
    | '/admin/settings'
    | '/api/health'
    | '/payment/$orderNumber'
    | '/products/$slug'
    | '/account'
    | '/admin'
    | '/products'
    | '/account/orders/$orderNumber'
    | '/admin/orders/$id'
    | '/account/orders'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/products'
    | '/register'
    | '/setup'
    | '/account/orders'
    | '/admin/activity'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/emails'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/api/health'
    | '/payment/$orderNumber'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/products/'
    | '/account/orders/$orderNumber'
    | '/admin/orders/$id'
    | '/account/orders/'
    | '/admin/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CartRouteRoute: typeof CartRouteRoute
  CheckoutRouteRoute: typeof CheckoutRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  RegisterRouteRoute: typeof RegisterRouteRoute
  SetupRouteRoute: typeof SetupRouteRoute
  ApiHealthRoute: typeof ApiHealthRoute
  PaymentOrderNumberRoute: typeof PaymentOrderNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/payment/$orderNumber': {
      id: '/payment/$orderNumber'
      path: '/payment/$orderNumber'
      fullPath: '/payment/$orderNumber'
      preLoaderRoute: typeof PaymentOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRouteRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountOrdersRouteRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRouteRoute
    }
    '/account/orders/$orderNumber': {
      id: '/account/orders/$orderNumber'
      path: '/$orderNumber'
      fullPath: '/account/orders/$orderNumber'
      preLoaderRoute: typeof AccountOrdersOrderNumberRouteImport
      parentRoute: typeof AccountOrdersRouteRoute
    }
  }
}

interface AccountOrdersRouteRouteChildren {
  AccountOrdersOrderNumberRoute: typeof AccountOrdersOrderNumberRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountOrdersRouteRouteChildren: AccountOrdersRouteRouteChildren = {
  AccountOrdersOrderNumberRoute: AccountOrdersOrderNumberRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountOrdersRouteRouteWithChildren =
  AccountOrdersRouteRoute._addFileChildren(AccountOrdersRouteRouteChildren)

interface AccountRouteRouteChildren {
  AccountOrdersRouteRoute: typeof AccountOrdersRouteRouteWithChildren
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountOrdersRouteRoute: AccountOrdersRouteRouteWithChildren,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminOrdersRouteRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteRouteChildren: AdminOrdersRouteRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteRouteWithChildren =
  AdminOrdersRouteRoute._addFileChildren(AdminOrdersRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminActivityRouteRoute: typeof AdminActivityRouteRoute
  AdminCategoriesRouteRoute: typeof AdminCategoriesRouteRoute
  AdminContentRouteRoute: typeof AdminContentRouteRoute
  AdminCouponsRouteRoute: typeof AdminCouponsRouteRoute
  AdminEmailsRouteRoute: typeof AdminEmailsRouteRoute
  AdminInventoryRouteRoute: typeof AdminInventoryRouteRoute
  AdminMediaRouteRoute: typeof AdminMediaRouteRoute
  AdminOrdersRouteRoute: typeof AdminOrdersRouteRouteWithChildren
  AdminProductsRouteRoute: typeof AdminProductsRouteRoute
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActivityRouteRoute: AdminActivityRouteRoute,
  AdminCategoriesRouteRoute: AdminCategoriesRouteRoute,
  AdminContentRouteRoute: AdminContentRouteRoute,
  AdminCouponsRouteRoute: AdminCouponsRouteRoute,
  AdminEmailsRouteRoute: AdminEmailsRouteRoute,
  AdminInventoryRouteRoute: AdminInventoryRouteRoute,
  AdminMediaRouteRoute: AdminMediaRouteRoute,
  AdminOrdersRouteRoute: AdminOrdersRouteRouteWithChildren,
  AdminProductsRouteRoute: AdminProductsRouteRoute,
  AdminSettingsRouteRoute: AdminSettingsRouteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ProductsRouteRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CartRouteRoute: CartRouteRoute,
  CheckoutRouteRoute: CheckoutRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  RegisterRouteRoute: RegisterRouteRoute,
  SetupRouteRoute: SetupRouteRoute,
  ApiHealthRoute: ApiHealthRoute,
  PaymentOrderNumberRoute: PaymentOrderNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
